### ISSUE TITLE
Remover Organizadores de um Evento

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/joyn2#47]
Como um organizador de um evento eu gostaria de remover outros usuários da lista de organizadores do evento.
* Eu só posso remover um organizador se eu também tiver a permissão de organizador.
* Uma mensagem de confirmação deve ser exibida antes de excluir o organizador.
* A conta do usuário deve continuar existindo como participante, ou como organizador (caso ele esteja organizando outro evento).

**Comment by iankakaruzia** [comment]
Testes Funcionais

Passos de Execução

1. Usuário deverá estar logado no sistema.
2. Ver detalhes do evento que será adicionado o Organizador.
3. Clica na opção excluir na frente do nome do Organizador a ser removido.
4. Confirma a remoção na mensagem de confirmação.
5. Será redirecionado para tela de visualização de detalhes do evento sem o Organizador removido.


![1 - Tela de Meus Eventos.jpg](https://zube.io/files/npi-ufc-qxd/3bdd100d67dd62b9c3c256579b2a0a46.jpeg)

1 - Tela de Meus Eventos

![2 - Tela de visualização de detalhes do evento.jpg](https://zube.io/files/npi-ufc-qxd/0aad115e439e8f79bb4ce239fd3dc5be.jpeg)

2 - Tela de visualização de detalhes do evento

![3 - Mensagem de confirmação de Remoção de Organizador.jpg](https://zube.io/files/npi-ufc-qxd/89f53a9b13a981b17daa1d2626365992.jpeg)

3 - Mensagem de confirmação de Remoção de Organizador

![4 - Tela após a remoção de Organizador.jpg](https://zube.io/files/npi-ufc-qxd/d431161a83125e4f9dc85a76717b92b1.jpeg)

4 - Tela após a remoção de Organizador
