### ISSUE TITLE
Criar atividade para evento

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/joyn2#48]
Eu como um organizador de um evento posso criar atividades para esse.
* Só podem criar atividades o usuário que tiver perfil de organizador do evento.
* Uma atividade possui as seguintes informações: nome, descrição, quantidade de vagas, quantidade de períodos de duração da atividade, tipo (check-in ou check-in/check-out), quantidade mínima de períodos para frequência, pontuação, status (ativa/inativa).
* Apenas os campos nome, descrição, períodos de duração da atividade, tipo e status são de preenchimento obrigatório.
* Quando o campo quantidade de vagas para a atividade for preenchido, a quantidade de inscrições será limitada por essa quantidade.
* Quando o organizador informar a quantidade de períodos de duração da atividade e o tipo de atividade o sistema deverá informar a quantidade de QR Codes que serão gerados; par atividades do tipo check-in/check-out a quantidade de QR Codes será calculado pela multiplicação da quantidade de períodos por 2, se for do tipo check-in multiplica-se por 1. Por exemplo, para uma atividade do tipo check-in com quantidade de períodos igual a 2, apenas 2 QR Codes serão gerados; para uma outra atividade do tipo check-in/check-out com 2 períodos de duração, 4 QR Codes sertão gerados.
* Após o sistema informar a quantidade de QR Codes que serão gerados o organizador escolherá a quantidade mínima de QR Codes necessários para garantir a frequência, levando em consideração que para atividades do tipo check-in/check-out são necessários 2 QR Codes para completar um período de atividade.

**Comment by fhugoduarte** [comment]
Retornar Feedback para o usuário caso ele cadastre uma atividade que ultrapasse a quantidade de vagas de um evento.

**Comment by iankakaruzia** [comment]
Testes Funcionais

Passos de Execução

1. Usuário deverá estar logado no sistema.
2. Usuário deverá ser organizador do evento.
3. Ver detalhes do evento que será criado uma atividade.
4. Clicar no botão Adicionar Atividades.
5.  Apoś a tentativa de cadastrar atividade sem nome, a tela permanecerá a mesma.
6. Apoś a tentativa de cadastrar atividade sem descrição, a tela permanecerá a mesma.
7. Apoś a tentativa de cadastrar atividade sem duração da atividade, a tela permanecerá a mesma.
8. Após o cadastro da atividade com todas as informações corretas, será redirecionado para a tela de visualizar detalhes da atividade.


![1 - Tela de Meus Eventos.jpg](https://zube.io/files/npi-ufc-qxd/7f8c6d91c85f99ab6b731b58afe01be4.jpeg)
1 - Tela de Meus Eventos

![2 - Tela de Detalhes do Evento.jpg](https://zube.io/files/npi-ufc-qxd/4ca05e568ff421cdc65b69b10d6421f9.jpeg)
2 - Tela de Detalhes do Evento

![3 - Tela de Cadastro de Atividade do Evento.jpg](https://zube.io/files/npi-ufc-qxd/4fd2f71f2baf6eb2935c8356b48c572b.jpeg)
3 - Tela de Cadastro de Atividade do Evento

![4 - Tela após tentativa de cadastro de atividade sem o nome.jpg](https://zube.io/files/npi-ufc-qxd/2e4bd1482e0809cd0314ed35ab66a67e.jpeg)
4 - Tela após tentativa de cadastro de atividade sem o nome

![5 - Tela de cadastro de Atividade sem a descrição.jpg](https://zube.io/files/npi-ufc-qxd/43a73226728ba7a7fde0b3d82860b646.jpeg)
5 - Tela de cadastro de Atividade sem a descrição

![6 - Tela de cadastro de atividade sem a duração.jpg](https://zube.io/files/npi-ufc-qxd/19fb8b5fcea30d36c11cb8e2223ffa66.jpeg)
6 - Tela de cadastro de atividade sem a duração

![7 - Tela de redirecionamento após cadastro realizado com sucesso.jpg](https://zube.io/files/npi-ufc-qxd/4bf897502bc940185cd935e80a446da3.jpeg)
7 - Tela de redirecionamento após cadastro realizado com sucesso
