### ISSUE TITLE
Detalhes da atividades

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/joyn2#49]
Como organizador, eu preciso ver detalhes das atividades de um evento.
* Apenas organizadores do evento poderão editar informações de atividades deste.
* A partir dos detalhes da atividade deve ser apresentado uma listagem dos participantes inscritos nela.
* O organizador poderá editar as informações do cadastro da atividade, obedecendo as regras estabelecidas no cadastro.

**Comment by iankakaruzia** [comment]
Testes Funcionais

Passos de Execução

1. Usuário deverá estar logado.
2. Usuário deverá ser Organizador de algum evento.
3. Deverá existir uma atividade cadastrada naquele evento.
4. Clicar em ver detalhes da atividade.


![1 - Tela de Meus eventos.jpg](https://zube.io/files/npi-ufc-qxd/f88889de9c3b712c294f2030a2ac9a20.jpeg)
1 - Tela de Meus eventos

![2 - Tela de Detalhes do Evento.jpg](https://zube.io/files/npi-ufc-qxd/86d87c228fb3ea15132475eff17e80f3.jpeg)
2 - Tela de Detalhes do Evento

![3 - Tela de detalhes da atividade.jpg](https://zube.io/files/npi-ufc-qxd/3f76161a1d1fd73d135553dff3c6632a.jpeg)
3 - Tela de detalhes da atividade
