### ISSUE TITLE
Editar atividade

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/joyn2#50]
Como organizador eu gostaria de editar informações de uma atividade.
* A edição da atividade poderá ser chamada a partir dos detalhes da atividade.
* Todos os campos podem ser modificados respeitando as regras do cadastro.
* Apenas organizadores associados ao evento poderão editar informações das atividades.

**Comment by iankakaruzia** [comment]
Testes Funcionais

Passos de Execução
	
1. Usuário deverá estar logado no sistema.
2. Usuário deverá ser organizador do evento.
3. Ver detalhes do evento que será criado uma atividade.
4. Clicar no botão ver detalhes da atividade a ser editada.
5. Clicar no botão editar a atividade.
6. Após a tentativa de editar atividade sem nome, a tela permanecerá a mesma.
7. Após a tentativa de editar atividade sem descrição, a tela permanecerá a mesma.
8. Após a tentativa de editar atividade sem duração da atividade, a tela permanecerá a mesma.
9. Após a edição da atividade com todas as informações corretas, será redirecionado para a tela de visualizar detalhes da atividade.


![1 - Tela de Meus Eventos.jpg](https://zube.io/files/npi-ufc-qxd/e5a2cca2e8a23d7a4e0dd324ce6c8e2d.jpeg)
1 - Tela de Meus Eventos

![2 - Tela de Detalhes do Evento.jpg](https://zube.io/files/npi-ufc-qxd/c7cb119753afe35ccb26b77f49c0b112.jpeg)
2 - Tela de Detalhes do Evento

![3 - Tela de Detalhes da Atividade.jpg](https://zube.io/files/npi-ufc-qxd/b9d66ee6c14a8226c1ba94b8feece7d2.jpeg)
3 - Tela de Detalhes da Atividade

![4 - Tela com formulário para edição de Atividade.jpg](https://zube.io/files/npi-ufc-qxd/831e9ea4b05956493406164ccaf6b36c.jpeg)
4 - Tela com formulário para edição de Atividade

![5 - Tela após tentativa de atualizar uma atividade sem nome.jpg](https://zube.io/files/npi-ufc-qxd/bb5f76086fa31f2d42c4c91469656785.jpeg)
5 - Tela após tentativa de atualizar uma atividade sem nome

![6 - Tela após tentativa de atualizar uma Atividade sem a descrição.jpg](https://zube.io/files/npi-ufc-qxd/606b9a9620b03b634be22855ce737cca.jpeg)
6 - Tela após tentativa de atualizar uma Atividade sem a descrição

![7 - Tela após tentativa de atualizar Atividade sem Duração.jpg](https://zube.io/files/npi-ufc-qxd/984f0e6f8eb3b8bc2e83ef50ab71fa81.jpeg)
7 - Tela após tentativa de atualizar Atividade sem Duração

![8 - Tela após Edição de Atividade bem sucedida.jpg](https://zube.io/files/npi-ufc-qxd/87ee8f40f265014a94ad6ee36875de5b.jpeg)
8 - Tela após Edição de Atividade bem sucedida
