### ISSUE TITLE
Excluir atividade

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/joyn2#51]
Como um organizador de um evento eu gostaria de excluir uma atividade adicionada ao evento.
* Uma atividade pode ser excluída a partir do detalhe do evento.
* Uma atividade só pode ser excluída por um organizador do evento que atividade está associada.
* Quando uma atividade for excluída todas as inscrições dos participantes também devem ser.
* Uma mensagem de confirmação deve ser apresentada antes de excluir a atividade.

**Comment by iankakaruzia** [comment]
Testes Funcionais

Passos de Execução

1. Usuário deverá estar logado no sistema.
2. Usuário deverá ser Organizador do Evento a ter a atividade excluída.
3. Visualizar detalhes do evento escolhido.
4. Excluir atividade Palestra Ionic 2 direto da tela de visualização de detalhes do evento.
5. Confirmar exclusão da atividade.
6. Na tela de detalhes do evento, clique em ver detalhes da atividade Palestra BigData.
7. Clique em excluir atividade.
8. Confirme a exclusão dessa atividade.
9. Será redirecionado para tela de visualização dos detalhes do evento.


![1 - Tela de Meus Eventos.jpg](https://zube.io/files/npi-ufc-qxd/32fe87b67c7ad0ffc1a3e220a1435203.jpeg)
1 - Tela de Meus Eventos

![2 - Tela de detalhes do evento.jpg](https://zube.io/files/npi-ufc-qxd/9e67d7015627446087f30c4753fa80fa.jpeg)
2 - Tela de detalhes do evento

![3 - Tela de confirmação de exclusão de atividade Ionic 2.jpg](https://zube.io/files/npi-ufc-qxd/abb858e73903e40badc084cbcc0a9f3b.jpeg)
3 - Tela de confirmação de exclusão de atividade Ionic 2

![4 - Tela após a exclusão da atividade Ionic 2.jpg](https://zube.io/files/npi-ufc-qxd/0e5390845611df32a703557244e9afb1.jpeg)
4 - Tela após a exclusão da atividade Ionic 2

![5 - Tela de visualização de detalhes da atividade.jpg](https://zube.io/files/npi-ufc-qxd/9ff770bcbc15363928fed97cea3d111a.jpeg)
5 - Tela de visualização de detalhes da atividade

![6 - Tela de confirmação de exclusão da atividade BigData.jpg](https://zube.io/files/npi-ufc-qxd/65d7106ea6a338f335b76a9d57c70adb.jpeg)
6 - Tela de confirmação de exclusão da atividade BigData

![7 - Tela de detalhes de eventos após exclusão da atividade BigData.jpg](https://zube.io/files/npi-ufc-qxd/bc35bbb70061ac922fcaeac904df6f61.jpeg)
7 - Tela de detalhes de eventos após exclusão da atividade BigData
