### ISSUE TITLE
Listar participantes do evento

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/joyn2#55]
Como organizador eu gostaria de visualizar a listagem dos participantes do evento.
* Apenas organizadores associados ao evento poderão ter acesso a listagem dos participantes.
* Deverão ser apresentados o nome, e-mail e foto do participante.
* A partir da listagem eu posso excluir a participação de um usuário em um evento.

**Comment by iankakaruzia** [comment]
Testes Funcionais

Passos de Execução

1. Usuário deverá estar logado no sistema.
2. Ver detalhes do evento que será listado os participantes.
3. Na tela de Visualizar detalhes do evento clica na opção Participantes.
4. É redirecionado para tela com listagem dos participantes do evento.


![1 - Tela de Meus Eventos.jpg](https://zube.io/files/npi-ufc-qxd/636551bd9153ffcbc6df3cf4af905402.jpeg)
1 - Tela de Meus Eventos

![2 - Tela de Visualizar detalhes de evento.jpg](https://zube.io/files/npi-ufc-qxd/97e3249fdec2f95f79c659ab350bb948.jpeg)
2 - Tela de Visualizar detalhes de evento

![3 - Tela de participantes do evento.jpg](https://zube.io/files/npi-ufc-qxd/c3b32196f1ecdb301b1aa6c172bf05e2.jpeg)
3 - Tela de participantes do evento
