### ISSUE TITLE
Excluir participante do evento

### ISSUE THREAD

**Issue by zarathon** [npi-ufc-qxd/joyn2#56]
Como organizador eu gostaria de excluir a inscrição de participantes do evento.
* Apenas organizadores associados ao evento poderão excluir participantes de um evento.
* Uma mensagem de confirmação deve ser exibida antes de excluir a participação em um evento.
* Caso o participante esteja inscrito em atividades do evento, essa inscrição também deverá ser excluída.

**Comment by iankakaruzia** [comment]
Testes Funcionais

Passos de Execução
	
1. Usuário deverá estar logado no sistema.
2. Usuário deverá ser Organizador do evento a ter seus participantes excluídos.
3. Visualizar detalhes do evento escolhido.
4. Clicar no botão Participantes para visualizar a tela com os Participantes do Evento.
5. Clicar no botão excluir em algum dos Participantes do Evento.
6. Confirmar exclusão do Participante naquele evento.
7. Tela será recarregada sem o Participante excluído.

![1 - Tela de Meus Eventos.jpg](https://zube.io/files/npi-ufc-qxd/bf236ce610f64f7fc6a341c617f20d6b.jpeg)
1 - Tela de Meus Eventos

![2 - Tela de detalhes do evento.jpg](https://zube.io/files/npi-ufc-qxd/650b51772ee768f7d9d701ddf06815a7.jpeg)
2 - Tela de detalhes do evento

![3 - Tela com lista de participantes do evento.jpg](https://zube.io/files/npi-ufc-qxd/26af2cdde7e16382a8bd3aa2e6ed1839.jpeg)
3 - Tela com lista de participantes do evento

![4 - Tela com mensagem de confirmação de exclusão de participantes.jpg](https://zube.io/files/npi-ufc-qxd/15d90a7f8aff783dab47732e3376edff.jpeg)
4 - Tela com mensagem de confirmação de exclusão de participantes

![5 - Tela após a exclusão do participante.jpg](https://zube.io/files/npi-ufc-qxd/4f1de7fb74fa2e1b341cdfcb0e0cdee4.jpeg)
5 - Tela após a exclusão do participante
